# -*- coding: utf-8 -*-
"""Chronos2-Retail_Substack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S4jJ_dtt1xkQzeksIPx8zajHujUjR87b

!pip install 'chronos-forecasting>=2.0'
"""

import pandas as pd
import numpy as np
import math
from pathlib import Path
import time

from sklearn.metrics import mean_squared_error
import holidays

import matplotlib.pyplot as plt
import seaborn as sns
from typing import Callable, Optional, Tuple, Dict, List, Any
from chronos import BaseChronosPipeline, Chronos2Pipeline

import torch
device = "mps" if torch.backends.mps.is_available() else ("cuda" if torch.cuda.is_available() else "cpu")
pipeline: Chronos2Pipeline = BaseChronosPipeline.from_pretrained("amazon/chronos-2", device_map=device)

from statsforecast import StatsForecast
from utilsforecast.losses import mae,smape,mse,mase,mqloss,rmse,rmae,rmsse,rmse,scaled_mqloss
from utilsforecast.evaluation import evaluate
from functools import partial
from scipy.signal import periodogram, find_peaks

from tqdm.autonotebook import tqdm

"""## Download Data

In this project, we'll use a dataset from the [Kaggle Tabular Playground Series - Sep 2022](https://www.kaggle.com/competitions/tabular-playground-series-sep-2022/data) competition

This dataset tracks daily sales of 4 books across 2 stores in 6 different countries, spanning over three years from 2017 to 2021. Our goal is to predict sales for each book, in each store, across every country.

A key strength of this dataset is that the test set includes the COVID-19 pandemic, which introduced **a major regime change** in sales patterns. This lets us evaluate how well the foundation model handles sudden, real-world changes.
"""

!unzip -o data-tabular-playground/tabular-playground-series-sep-2022.zip -d data-tabular-playground/

DATAPATH = Path("data-tabular-playground")
data = pd.read_csv(DATAPATH / "train.csv")
data['date']  = pd.to_datetime(data['date'])

"""## Preprocessing

Next, we add a unique identifier for each time-series — a combination of country, store, and product:
"""

data['unique_id'] = data['country'].astype(str) + "_" + data['store'].astype(str) + "_" + data['product'].astype(str)
data

# Add Calendar-based features
data['day'] = data['date'].dt.weekday + 1   # Monday=1 … Sunday=7
data['month'] = data['date'].dt.month #[1-12]

# countryto ISO code map for holidays
country_code_map = {
    'Belgium': 'BE',
    'France':  'FR',
    'Germany': 'DE',
    'Italy':   'IT',
    'Poland':  'PL',
    'Spain':   'ES',
}

years = data['date'].dt.year.unique().tolist()

# instantiate a holiday calendar per country - we have 6 different countries in our dataset
country_holidays = { country: holidays.CountryHoliday(code, years=years) for country, code in country_code_map.items()}
data['holiday_name'] = 'noholiday' #default when there's no holiday

for country, cal in country_holidays.items():
    mask = data['country'] == country

    # pull pure date objects to match calendar's keys
    dates = data.loc[mask, 'date'].dt.date

    # map each date to holiday name or 'noholiday'
    data.loc[mask, 'holiday_name'] = dates.map(lambda d: cal.get(d, 'noholiday'))

# derive is_holiday from holiday_name
data['is_holiday'] = (data['holiday_name'] != 'noholiday')*1
data

"""Number of rows per unique key:"""

data['unique_id'].value_counts()

"""## Exploratory Data Analysis"""

x = data.groupby(['date', 'country'])['num_sold'].sum().reset_index()
sns.set_theme(style="whitegrid", palette="Accent")
plt.figure(figsize=(15, 7)); sns.lineplot(data=x, x='date', y='num_sold', hue='country')
plt.title("Total Units Sold per Country", fontsize=14, weight='bold');
plt.xticks(rotation=45);
plt.tight_layout()

x = data.groupby(['date', 'store'])['num_sold'].sum().reset_index()
sns.set_theme(style="whitegrid", palette="Accent")
plt.figure(figsize=(15, 7)); sns.lineplot(data=x, x='date', y='num_sold', hue='store')
plt.title("Total Units Sold per Store", fontsize=14, weight='bold');
plt.xticks(rotation=45);
plt.tight_layout()

x = data.groupby(['date'])['num_sold'].sum().reset_index()
sns.set_theme(style="whitegrid")
plt.figure(figsize=(22, 7)); sns.lineplot(data=x, x='date', y='num_sold')
plt.title("Total Sales Across All Products and Stores", fontsize=14, weight='bold');
plt.xticks(rotation=45);

"""## Helper Functions"""

def split_train_test(df, context_length, TEST):

    cutoff = df.sort_values(['unique_id','ds'])['ds'].values[-TEST]
    Y_test_df = df[df.ds >= cutoff].sort_values(['unique_id','ds'])
    Y_train_df = (
        df[df['ds'] < cutoff]
        .sort_values(['unique_id','ds'])
        .groupby('unique_id', group_keys=False)
        .filter(lambda g: len(g) >= context_length)
        .groupby('unique_id', group_keys=False)
        .tail(context_length)
        .reset_index(drop=True)
    )

    if Y_train_df.empty:
        print("Warning: Y_train_df is empty — check context_length or data before cutoff.")
    if Y_test_df.empty:
        print("Warning: Y_test_df is empty — check TEST size or dataset length.")

    return Y_train_df, Y_test_df



def plot_timeseries(inputs, point_forecast, actuals=None, n_series_to_plot=4, intervals=False):
    """
    Plot time series with inputs, forecasts (or quantile intervals), and optional actuals.
    If intervals=True, point_forecast is a quantile tensor (n_series, horizon, n_quantiles).
    Returns a DataFrame with per-series MSE (computed for all series).
    The MSE will be calculated for each series, and n_series_to_plot determines how many of them will be visualized.
    """
    n_series = len(inputs)
    plot_count = min(n_series_to_plot, n_series)
    n_cols = 2 if plot_count > 1 else 1
    n_rows = math.ceil(plot_count / n_cols) if plot_count > 0 else 0

    fig, axes = (plt.subplots(n_rows, n_cols, figsize=(8 * n_cols, 4 * n_rows), squeeze=False) if plot_count > 0 else (None, None))
    results = []

    for idx in range(n_series):
        input_len = len(inputs[idx])

        if intervals:
            q10, q50, q90 = point_forecast[idx][:, 0], point_forecast[idx][:, 4], point_forecast[idx][:, 8]
            forecast_len, pred_mean = len(q50), q50
        else:
            forecast_len, pred_mean = len(point_forecast[idx]), point_forecast[idx]

        actual_len = len(actuals[idx]) if actuals is not None else 0
        mse = (mean_squared_error(actuals[idx][:min(len(pred_mean), len(actuals[idx]))], pred_mean[:min(len(pred_mean), len(actuals[idx]))]) if actuals is not None else np.nan)

        results.append({"series_id": idx, "mse": mse, "input_len": input_len, "forecast_len": forecast_len, "actual_len": actual_len})

        # Plot only subset
        if idx < plot_count:
            ax = axes[idx // n_cols, idx % n_cols]
            ax.plot(range(input_len), inputs[idx], label='Input', color='#1f77b4', marker='o', markersize=3)
            if actuals is not None:
                ax.plot(range(input_len, input_len + actual_len), actuals[idx], label='Actual', color='#2ca02c', marker='x', markersize=4)
            if intervals:
                x = np.arange(input_len, input_len + forecast_len)
                ax.fill_between(x, q10, q90, color='#ff7f0e', alpha=0.25, label='P10–P90 Interval')
                ax.plot(x, q50, color='#B41F77', label='Median (P50)', marker='s', markersize=4)
            else:
                ax.plot(range(input_len, input_len + forecast_len), pred_mean, label='Forecast', color='#B41F77', marker='s', markersize=4)
            ax.set_title(f"Series {idx+1} | MSE={mse:.3f}" if not np.isnan(mse) else f"Series {idx+1}", fontsize=11)
            ax.legend(fontsize=8)
            ax.grid(True, linestyle='--', alpha=0.4)

    # Remove empty subplots
    if plot_count > 0:
        for j in range(plot_count, n_rows * n_cols):
            fig.delaxes(axes[j // n_cols, j % n_cols])
        plt.tight_layout()
        plt.show()
    return pd.DataFrame(results)

## Let's use Nixtla's naming format
df=data.copy()
df.rename(columns={"date":"ds","num_sold":"y"},inplace=True)

context_length=1300
prediction_length=24
num_windows = 1
TEST = prediction_length * num_windows
quantile_levels = [i/10 for i in range(1, 10)]

Y_train_df, Y_test_df =  split_train_test(df, context_length, TEST)

#verify dataset lengths
item_list = df['unique_id'].unique().tolist()
assert ( (len(Y_train_df), len(Y_test_df))== ( len(item_list)*context_length, len(item_list)*prediction_length ))

"""### Case 1: Multivariate Forecasting

Input format: list containing a single dict. The dict contains a single key (target) whose value contains the inputs (context_lengths) of len(item_list) time series (items)

```python
inputs = [
    {
        "target": np.array((len(item_list), len(context_len)))
    }
]
```
"""

inputs = [{"target": np.stack([Y_train_df[Y_train_df["unique_id"]==item]["y"].to_numpy() for item in item_list])}]
actuals = [{"target": np.stack([Y_test_df[Y_test_df["unique_id"]==item]["y"].to_numpy() for item in item_list])}]

quantiles, mean = pipeline.predict_quantiles( inputs, prediction_length=prediction_length, quantile_levels=quantile_levels )
print("Multivariate, output shapes of each item:", quantiles[0].shape, mean[0].shape)
print("Total Forecast Runs", len(quantiles))

#format them to list of numpy arrays in order to plo them
inputs_list = [arr for arr in inputs[0]["target"]]
actuals_list = [arr for arr in actuals[0]["target"]]

df_mse = plot_timeseries(inputs_list, quantiles[0], actuals_list, n_series_to_plot=2,intervals=True)

print(f"Mean MSE of Chronos Multivariate: {df_mse["mse"].mean()}")

"""### Case 2: Univariate Forecasting

Input format: list of dicts (each dict being a time series)

```python
inputs = [
    {
        "target": np.array(len(context_len))
    }
    ....    
]
```
"""

inputs, actuals = [], []
for _, item in enumerate(item_list):

    item_data_train = Y_train_df[(Y_train_df["unique_id"] == item) ]
    item_data_test = Y_test_df[(Y_test_df["unique_id"] == item) ]

    item_data_train_dict ={"target":item_data_train["y"].to_numpy()}
    item_data_test_dict ={"target":item_data_test["y"].to_numpy()}


    inputs.append(item_data_train_dict)
    actuals.append(item_data_test_dict)


quantiles, mean = pipeline.predict_quantiles( inputs, prediction_length=prediction_length, quantile_levels=quantile_levels)
print("Univariate, output shapes of each item:", quantiles[0].shape, mean[0].shape)
print("Total items", len(quantiles))

"""Also format the below for plotting"""

quantiles = torch.stack(quantiles).squeeze(1)
quantiles.shape

inputs_f = [v["target"] for v in inputs]
actuals_f = [v["target"] for v in actuals]

df_mse = plot_timeseries(inputs_f, quantiles, actuals_f, n_series_to_plot=2,intervals=True)

print(f"Mean MSE of Chronos over all time-series: {df_mse["mse"].mean()}")
#2087.125122388204

"""Notice that if we set `predict_batches_jointly=True`, we enable cross-learining, achieving the same score with multivariate"""

quantiles, mean = pipeline.predict_quantiles( inputs, prediction_length=prediction_length, quantile_levels=quantile_levels, predict_batches_jointly=True)
print("Univariate, output shapes of each item:", quantiles[0].shape, mean[0].shape)
print("Total items", len(quantiles))

quantiles = torch.stack(quantiles).squeeze(1)
inputs_f = [v["target"] for v in inputs]
actuals_f = [v["target"] for v in actuals]

df_mse = plot_timeseries(inputs_f, quantiles, actuals_f, n_series_to_plot=2,intervals=True)

print(f"Mean MSE of Chronos over all time-series: {df_mse["mse"].mean()}")

"""### Case 3: Univariate Forecasting + Covariates

Input format: list of dicts (each dict being a time series)

```python
inputs = [
    {
        "target": np.array(len(context_len))
            "past_covariates": {
            "numerical_covariate1": len(context_len),
            "categorical_covariate": len(context_len),
        },
        "future_covariates": {
            "numerical_covariate1": len(prediction_len),
            "categorical_covariate": len(prediction_len),
        },
    }
    ....    
]
```
"""

inputs, actuals = [], []
for _, item in enumerate(item_list):

    item_data_train = Y_train_df[(Y_train_df["unique_id"] == item) ]
    item_data_test = Y_test_df[(Y_test_df["unique_id"] == item) ]


    item_data_train_dict ={
                "target":item_data_train["y"].to_numpy(),
                "past_covariates":
                                    {"day": item_data_train["day"].astype(int).to_numpy(),
                                    "month": item_data_train["month"].astype(int).to_numpy(),
                                    "is_holiday": item_data_train["is_holiday"].astype(int).to_numpy(),
                                    "country": item_data_train["country"].to_numpy(),
                                    "store": item_data_train["store"].to_numpy(),
                                    "product": item_data_train["product"].to_numpy(),
                                    "holiday_name": item_data_train["holiday_name"].to_numpy(),
                                    },

                "future_covariates":
                                    {"day": item_data_test["day"].astype(int).to_numpy(),
                                    "month": item_data_test["month"].astype(int).to_numpy(),
                                    "is_holiday": item_data_test["is_holiday"].astype(int).to_numpy(),
                                    "country": item_data_test["country"].to_numpy(),
                                    "store": item_data_test["store"].to_numpy(),
                                    "product": item_data_test["product"].to_numpy(),
                                    "holiday_name": item_data_test["holiday_name"].to_numpy(),
                                    },
                                    }
    item_data_test_dict ={"target":item_data_test["y"].to_numpy()}


    inputs.append(item_data_train_dict)
    actuals.append(item_data_test_dict)

quantiles, mean = pipeline.predict_quantiles(inputs, prediction_length=prediction_length, quantile_levels=quantile_levels )
print("Univariate + Covariates, output shapes of each item:", quantiles[0].shape, mean[0].shape)
print("Total items", len(quantiles))

quantiles = torch.stack(quantiles).squeeze(1)
inputs_f = [v["target"] for v in inputs]
actuals_f = [v["target"] for v in actuals]

df_mse = plot_timeseries(inputs_f, quantiles, actuals_f, n_series_to_plot=2,intervals=True)

print(f"Mean MSE of Chronos over all time-series: {df_mse["mse"].mean()}")

"""### Case 4: Multivariate Forecasting + Covariates (Cross-Learning)

Inputs stay the same, we only add `predict_batches_jointly=True`
"""

quantiles, mean = pipeline.predict_quantiles(inputs, prediction_length=prediction_length, quantile_levels=quantile_levels, predict_batches_jointly=True)
print("Multivariate + Covariates, output shapes of each item:", quantiles[0].shape, mean[0].shape)
print("Total items", len(quantiles))

quantiles = torch.stack(quantiles).squeeze(1)
inputs_f = [v["target"] for v in inputs]
actuals_f = [v["target"] for v in actuals]

df_mse = plot_timeseries(inputs_f, quantiles, actuals_f, n_series_to_plot=2,intervals=True)

print(f"Mean MSE of Chronos over all time-series: {df_mse["mse"].mean()}")
#Mean MSE of Chronos over all time-series: 1200.1404182116191

"""### Final Case: Create a unifying API to call Chronos

Let's create a single function that'll cover every case:
"""

context_length=1300
prediction_length=24
num_windows = 1
TEST = prediction_length * num_windows

Y_train_df, Y_test_df =  split_train_test(df, context_length, TEST)

#verify dataset lengths
item_list = df['unique_id'].unique().tolist()
assert ( (len(Y_train_df), len(Y_test_df))== ( len(item_list)*context_length, len(item_list)*prediction_length ))

# chronos_forecast unifies all Chronos forecast cases into one — note how covariates are handled:
# if past and future covariates are identical, pass the same list/dict; otherwise, use separate ones.

def chronos_forecast(Y_train_df,
                     Y_test_df,
                     item_list,
                     prediction_length,
                     quantile_levels,
                     covariates=None,         # None | list | (past_list, future_list) | dict {'past': [...], 'future': [...]}
                     cross_learning=False,
                     verbose=True):
    """
    regrading covariates:
      - None or False -> no covariates
      - list -> same columns used for both past & future covariates
      - tuple/list of length 2 -> (past_cols, future_cols)
      - dict -> may contain keys 'past' and/or 'future' mapping to lists of column names
    """

    def _get_col_lists(cov):
        if not cov:
            return [], []
        # accept a 2-tuple/list as (past_cols, future_cols)
        if isinstance(cov, (list, tuple)) and len(cov) == 2 and all(isinstance(x, (list, tuple)) for x in cov):
            past_cols = list(cov[0])
            future_cols = list(cov[1])
        elif isinstance(cov, dict):
            past_cols = cov.get("past") or cov.get("past_covariates") or []
            future_cols = cov.get("future") or cov.get("future_covariates") or []
        else:
            # single list -> use same for both
            past_cols = list(cov)
            future_cols = list(cov)
        return past_cols, future_cols

    inputs, actuals = [], []
    past_cols, future_cols = _get_col_lists(covariates)

    for _, item in enumerate(item_list):
        item_data_train = Y_train_df[Y_train_df["unique_id"] == item]
        item_data_test = Y_test_df[Y_test_df["unique_id"] == item]

        item_data_train_dict = {"target": item_data_train["y"].to_numpy()}
        item_data_test_dict = {"target": item_data_test["y"].to_numpy()}

        if covariates:
            past_cov_dict = {}
            future_cov_dict = {}

            # Build past covariates from train rows
            for col in past_cols:
                if col not in item_data_train.columns:
                    print(f"[warning] past covariate '{col}' not present for item {item} -> skipping")
                    continue
                past_cov_dict[col] = item_data_train[col].to_numpy()

            # Build future covariates from test rows
            for col in future_cols:
                if col not in item_data_test.columns:
                    print(f"[warning] future covariate '{col}' not present for item {item} -> skipping")
                    continue
                future_cov_dict[col] = item_data_test[col].to_numpy()

            if past_cov_dict:
                item_data_train_dict["past_covariates"] = past_cov_dict
            if future_cov_dict:
                item_data_train_dict["future_covariates"] = future_cov_dict

        inputs.append(item_data_train_dict)
        actuals.append(item_data_test_dict)

    quantiles, mean = pipeline.predict_quantiles(
        inputs,
        prediction_length=prediction_length,
        quantile_levels=quantile_levels,
        predict_batches_jointly=cross_learning
    )
    quantiles = torch.stack(quantiles).squeeze(1)
    mean = torch.stack(mean).squeeze(1)

    if verbose:
        print("Output shapes of each item:", quantiles[0].shape, mean[0].shape)
        print("Total items", len(quantiles))

    return quantiles, mean, inputs, actuals

"""#### Case 1: Multivariate Forecasting"""

quantiles, mean, inputs, actuals = chronos_forecast(Y_train_df, Y_test_df, item_list, prediction_length=prediction_length, quantile_levels=quantile_levels,covariates=None, cross_learning=True)
#quantiles = torch.stack(quantiles).squeeze(1)
inputs_f = [v["target"] for v in inputs]
actuals_f = [v["target"] for v in actuals]

df_mse = plot_timeseries(inputs_f, quantiles, actuals_f, n_series_to_plot=0,intervals=True)
print(f"Mean MSE of Chronos over all time-series: {df_mse["mse"].mean()}")
#Mean MSE of Chronos over all time-series: 1635.6124127705891

"""#### Case 2: Univariate Forecasting"""

quantiles, mean, inputs, actuals = chronos_forecast(Y_train_df, Y_test_df, item_list,  prediction_length=prediction_length, quantile_levels=quantile_levels, covariates=None, cross_learning=False)
#quantiles = torch.stack(quantiles).squeeze(1)
inputs_f = [v["target"] for v in inputs]
actuals_f = [v["target"] for v in actuals]

df_mse = plot_timeseries(inputs_f, quantiles, actuals_f, n_series_to_plot=0,intervals=True)
print(f"Mean MSE of Chronos over all time-series: {df_mse["mse"].mean()}")
#Mean MSE of Chronos over all time-series: 2087.125122388204

"""#### Case 3: Univariate Forecasting + Covariates"""

cols = ["day","month","is_holiday","country","store","product","holiday_name"]
quantiles, mean, inputs, actuals = chronos_forecast(Y_train_df, Y_test_df, item_list,  prediction_length=prediction_length, quantile_levels=quantile_levels, covariates=cols, cross_learning=False)
#quantiles = torch.stack(quantiles).squeeze(1)
inputs_f = [v["target"] for v in inputs]
actuals_f = [v["target"] for v in actuals]

df_mse = plot_timeseries(inputs_f, quantiles, actuals_f, n_series_to_plot=0,intervals=True)
print(f"Mean MSE of Chronos over all time-series: {df_mse["mse"].mean()}")
#Mean MSE of Chronos over all time-series: 1369.2051642735798

"""#### Case 4: Multivariate Forecasting + Covariates (Cross-Learning)"""

cols = ["day","month","is_holiday","country","store","product","holiday_name"]
quantiles, mean, inputs, actuals = chronos_forecast(Y_train_df, Y_test_df, item_list,  prediction_length=prediction_length, quantile_levels=quantile_levels, covariates=cols, cross_learning=True)
#quantiles = torch.stack(quantiles).squeeze(1)
inputs_f = [v["target"] for v in inputs]
actuals_f = [v["target"] for v in actuals]

df_mse = plot_timeseries(inputs_f, quantiles, actuals_f, n_series_to_plot=0,intervals=True)
print(f"Mean MSE of Chronos over all time-series: {df_mse["mse"].mean()}")
#Mean MSE of Chronos over all time-series: 1200.1404182116191

"""### Chronos vs Statistical Models

#### Helper Functions
"""

def plot_multiple_timeseries(train_data, predictions, item_ids_to_plot, model, plot_intervals):

    """
    Plots multiple time series for given items, including historical data, forecasts, and observed values.

    This function generates subplots for each item in `item_ids_to_plot`, displaying:
    - The historical time series data.
    - The model's forecast.
    - The observed values (if available).

    Parameters:
    -----------
    train_data : pandas.DataFrame
        DataFrame containing historical time series data. It should have the columns `unique_id`, `ds` (date), and `y` (values).
    predictions : pandas.DataFrame
        DataFrame containing forecasted values. It should have the same structure as `train_data`, with additional columns for model predictions and confidence intervals.
    item_ids_to_plot : list
        A list of `unique_id`s for the items to plot.
    model : str
        The name of the model used for forecasting, which should correspond to columns in the `predictions` DataFrame.
    plot_intervals : bool
        If `True`, the function will plot the 10%-90% prediction intervals for the forecasts.

    Returns:
    --------
    None
        The function displays the plots and does not return any values.
    """

    BLUE, PURPLE, LIGHT_PURPLE, PINK = '#3598ec', '#7463e1', '#d7c3ff', '#ff0099'

    n = len(item_ids_to_plot)
    if n == 0:
        return

    # each subplot on its own row
    fig, axes = plt.subplots(nrows=n, ncols=1, figsize=(13, 4 * n))
    if n == 1:
        axes = [axes]

    for i, item_id in enumerate(item_ids_to_plot):
        ax = axes[i]

        y_past = train_data.set_index(['unique_id', 'ds']).loc[item_id]['y'][-500:]
        y_pred = predictions.loc[item_id]
        y_test = predictions.loc[item_id]["y"]

        ax.plot(y_past, label="Past Time Series", color=BLUE, linestyle='-')
        ax.plot(y_pred[model], label="Forecast", color=PURPLE, linestyle='--')
        ax.plot(y_test, label="Observed", color=BLUE, linestyle='-')

        ax.axvline(x=y_pred.index[0], color='red', linestyle='--', label="Prediction Start")

        # Prediction intervals
        if plot_intervals:
            ax.fill_between( y_pred.index, y_pred[model + "-lo-80"], y_pred[model + "-hi-80"], color=LIGHT_PURPLE, alpha=0.3, label="10th-90th Test Prediction Interval")

        ax.legend()
        ax.set_xlabel("Time")
        ax.set_ylabel("Value")
        ax.set_title(f"Predictions for Item {item_id}")
        ax.grid(True, linestyle=':', alpha=0.4)

    plt.tight_layout()
    plt.show()

def cross_validate_fm(
    Y_train_df: pd.DataFrame,
    Y_test_df: pd.DataFrame,
    prediction_length: int,
    context_length: int,
    windows: Optional[int] = None,
    covariates: Optional[object] = None,
    cross_learning: bool = False,
    chronos_forecast_func = None,
    model_prefix: str = "chronos",
    verbose: bool = False,
) -> pd.DataFrame:
    """
    Rolling-origin CV that slices Nixtla-style dataframes per window and calls chronos_forecast once per window.

    context_length: maximum number of past rows per series to keep (train + test-prefix). If a series has fewer rows,
                    all available rows are kept.
    chronos_forecast_func must accept:
      (Y_train_df_w, Y_test_df_w, item_list, covariates, cross_learning, prediction_length, quantile_levels)
    and return (quantiles, mean, inputs, actuals).
    """

    required_cols = {"unique_id", "ds", "y"}
    if not required_cols.issubset(Y_train_df.columns) or not required_cols.issubset(Y_test_df.columns):
        raise ValueError(f"Both Y_train_df and Y_test_df must contain columns {required_cols}")

    if context_length is None or int(context_length) <= 0:
        raise ValueError("context_length must be a positive integer")

    context_length = int(context_length)

    Y_train_df = Y_train_df.sort_values(["unique_id", "ds"]).reset_index(drop=True)
    Y_test_df = Y_test_df.sort_values(["unique_id", "ds"]).reset_index(drop=True)

    series_ids = sorted(Y_test_df["unique_id"].unique())

    # ensure every test series exists in train map (may be empty)
    empty_train_template = pd.DataFrame(columns=Y_train_df.columns)
    train_groups = {uid: grp.sort_values("ds").reset_index(drop=True) for uid, grp in Y_train_df.groupby("unique_id")}
    for uid in series_ids:
        if uid not in train_groups:
            train_groups[uid] = empty_train_template.copy()

    horizons = {uid: len(grp) for uid, grp in Y_test_df.groupby("unique_id")}
    if len(set(horizons.values())) != 1:
        raise ValueError(f"All series must have the same test horizon length. Found per-series lengths: {horizons}")
    total_horizon = next(iter(set(horizons.values())))

    if windows is None:
        windows = math.ceil(total_horizon / prediction_length)
    else:
        windows = int(windows)
        if windows < 1:
            raise ValueError("windows must be >= 1")

    if chronos_forecast_func is None:
        chronos_forecast_func = globals().get("chronos_forecast")
        if chronos_forecast_func is None:
            raise ValueError("chronos_forecast function not provided and not found in globals().")

    records = []
    # We hardcode these here, feel free to change them
    levels = [0.1, 0.5, 0.9]

    for w in tqdm(range(windows), desc="Processing windows"):
        start = w * prediction_length
        remaining = total_horizon - start
        if remaining <= 0:
            break
        horizon_this_window = min(prediction_length, remaining)

        if verbose:
            print(f"[cv] window {w+1}/{windows}: start={start}, horizon={horizon_this_window}")

        # build Y_test_df_w: per-series slice [start : start + horizon_this_window]
        Y_test_df_w = (
            Y_test_df
            .groupby("unique_id", group_keys=False)
            .apply(lambda g: g.iloc[start : start + horizon_this_window])
            .reset_index(drop=True)
        )

        # build test_prefix (to append to train) = per-series test prefix [:start]
        # only the first window will use the Y_train_df as input
        if start == 0:
            combined_train = Y_train_df.copy()
        else:
            test_prefix = (
                Y_test_df
                .groupby("unique_id", group_keys=False)
                .apply(lambda g: g.iloc[:start])
                .reset_index(drop=True)
            )
            combined_train = pd.concat([Y_train_df, test_prefix], axis=0, ignore_index=True)

        # Also, we truncate each series to use the last `context_length` rows
        Y_train_df_w = (
            combined_train
            .sort_values(["unique_id", "ds"])
            .groupby("unique_id", group_keys=False)
            .apply(lambda g: g.iloc[-context_length:])
            .reset_index(drop=True)
        )

        # ensure ordering on both train and test windows
        Y_train_df_w = Y_train_df_w.sort_values(["unique_id", "ds"]).reset_index(drop=True)
        Y_test_df_w = Y_test_df_w.sort_values(["unique_id", "ds"]).reset_index(drop=True)

        # call chronos_forecast once per window
        quantiles_out, mean_out, inputs_out, actuals_out = chronos_forecast_func(
            Y_train_df_w,
            Y_test_df_w,
            item_list=series_ids,
            prediction_length=horizon_this_window,
            quantile_levels=levels,
            covariates=covariates,
            cross_learning=cross_learning,
            verbose=verbose
        )

        q_np = np.asarray(quantiles_out)
        m_np = np.asarray(mean_out)

        if q_np.ndim != 3 or m_np.ndim != 2:
            raise RuntimeError(f"Unexpected shapes from chronos_forecast: quantiles {q_np.shape}, mean {m_np.shape}")

        N, H, Q = q_np.shape
        if H != horizon_this_window:
            raise RuntimeError(f"Predict output horizon H={H} != expected {horizon_this_window}")
        if N != len(series_ids):
            raise RuntimeError(f"Predict output batch size N={N} != number of series {len(series_ids)}")


        q10_arr = q_np[:, :, levels.index(0.1)] # 10-th quantile
        q50_arr = q_np[:, :,  levels.index(0.5)] # median
        q90_arr = q_np[:, :, levels.index(0.9)] # 90-th quantile

        grouped_test_w = {uid: grp.reset_index(drop=True) for uid, grp in Y_test_df_w.groupby("unique_id")}

        for s_idx, uid in enumerate(series_ids):
            test_slice = grouped_test_w[uid]
            ds_arr = test_slice["ds"].to_numpy()
            y_arr = test_slice["y"].to_numpy()
            for h in range(horizon_this_window):
                records.append({
                    "unique_id": uid,
                    "ds": ds_arr[h],
                    "y": float(y_arr[h]),
                    f"{model_prefix}-50": float(q50_arr[s_idx, h]),
                    f"{model_prefix}-10": float(q10_arr[s_idx, h]),
                    f"{model_prefix}-90": float(q90_arr[s_idx, h]),
                })

    out_df = pd.DataFrame.from_records(records)
    out_df = out_df.sort_values(["unique_id", "ds"]).reset_index(drop=True)
    return out_df

"""#### Let's start small, with a single window first

##### Case 1: Multivariate Forecasting
"""

#We set those earlier, let's set them again

context_length=1300
prediction_length=24
num_windows = 1
TEST = prediction_length * num_windows

Y_train_df, Y_test_df =  split_train_test(df, context_length, TEST)

results_chronos_mv_df = cross_validate_fm(
    Y_train_df=Y_train_df,
    Y_test_df=Y_test_df,
    prediction_length=prediction_length,
    context_length=context_length,
    windows=None,
    covariates=None,
    cross_learning=True,
    chronos_forecast_func=chronos_forecast,
    model_prefix="chronos",
    verbose=False,
)
results_chronos_mv_df.rename(columns={'chronos-50': 'chronos','chronos-10':'chronos-lo-80', 'chronos-90':'chronos-hi-80'}, inplace=True)

seasonality=7
mase_seas = partial(mase, seasonality=seasonality)

chronos_mv_df = evaluate(df=results_chronos_mv_df, metrics=[smape,mae,mse,mase_seas,rmse,mqloss], train_df=Y_train_df,  models=['chronos'],level=[80],agg_fn='mean')
chronos_mv_df

"""##### Case 2: Univariate Forecasting"""

results_chronos_uni_df = cross_validate_fm(
    Y_train_df=Y_train_df,
    Y_test_df=Y_test_df,
    prediction_length=24,
    context_length=1300,
    windows=None,
    covariates=None,
    cross_learning=False,
    chronos_forecast_func=chronos_forecast,
    model_prefix="chronos",
    verbose=True,
)
results_chronos_uni_df.rename(columns={'chronos-50': 'chronos','chronos-10':'chronos-lo-80', 'chronos-90':'chronos-hi-80'}, inplace=True)

seasonality=7
mase_seas = partial(mase, seasonality=seasonality)

chronos_uni_df = evaluate(df=results_chronos_uni_df, metrics=[smape,mae,mse,mase_seas,rmse,mqloss], train_df=Y_train_df,  models=['chronos'],level=[80],agg_fn='mean')
chronos_uni_df

"""##### Case 3: Univariate Forecasting + Covariates"""

results_chronos_uni_cov_df = cross_validate_fm(
    Y_train_df=Y_train_df,
    Y_test_df=Y_test_df,
    prediction_length=24,
    context_length=1300,
    windows=None,
     covariates=["day","month","is_holiday","country","store","product","holiday_name"],
    cross_learning=False,
    chronos_forecast_func=chronos_forecast,
    model_prefix="chronos",
    verbose=True,
)
results_chronos_uni_cov_df.rename(columns={'chronos-50': 'chronos','chronos-10':'chronos-lo-80', 'chronos-90':'chronos-hi-80'}, inplace=True)

chronos_uni_cov_df = evaluate(df=results_chronos_uni_cov_df, metrics=[smape,mae,mse,mase_seas,rmse,mqloss], train_df=Y_train_df,  models=['chronos'],level=[80],agg_fn='mean')
chronos_uni_cov_df

"""##### Case 4: Multivariate Forecasting + Covariates (Cross-Learning)"""

results_chronos_mv_cov_df = cross_validate_fm(
    Y_train_df=Y_train_df,
    Y_test_df=Y_test_df,
    prediction_length=24,
    context_length=1300,
    windows=None,
    covariates=["day","month","is_holiday","country","store","product","holiday_name"],
    cross_learning=True,
    chronos_forecast_func=chronos_forecast,
    model_prefix="chronos",
    verbose=True,
)
results_chronos_mv_cov_df.rename(columns={'chronos-50': 'chronos','chronos-10':'chronos-lo-80', 'chronos-90':'chronos-hi-80'}, inplace=True)

chronos_mv_cov_df = evaluate(df=results_chronos_mv_cov_df, metrics=[smape,mae,mse,mase_seas,rmse,mqloss], train_df=Y_train_df,  models=['chronos'],level=[80],agg_fn='mean')
chronos_mv_cov_df

"""#### Let's now do 10 windows

##### Context-length=1000
"""

context_length=1000
prediction_length=24
num_windows = 10
TEST = prediction_length * num_windows

Y_train_df, Y_test_df =  split_train_test(df, context_length, TEST)

# Case 1: Multivariate Forecasting
start_times_chronos_mv = time.time()
results_chronos_mv_df = cross_validate_fm(
    Y_train_df=Y_train_df,
    Y_test_df=Y_test_df,
    prediction_length=prediction_length,
    context_length=context_length,
    windows=None,
    covariates=None,
    cross_learning=True,
    chronos_forecast_func=chronos_forecast,
    model_prefix="chronos",
    verbose=False,
)
end_times_chronos_mv = time.time()
print(f"Case 1 - Multivariate Forecasting (Chronos) Execution time: {int((end_times_chronos_mv - start_times_chronos_mv) // 60)} min {(end_times_chronos_mv - start_times_chronos_mv) % 60:.2f} sec")

##################### let's calculate some assertions to be sure ###################
assert(np.allclose(results_chronos_mv_df["y"], Y_test_df["y"]))
assert np.array_equal(results_chronos_mv_df["ds"].to_numpy(), Y_test_df["ds"].to_numpy())
#make sure the generated baseline predcitions have the correct lengths
assert len(results_chronos_mv_df) == len(df["unique_id"].unique().tolist()) * TEST


# Case 2: Univariate Forecasting
start_times_chronos_uni = time.time()
results_chronos_uni_df = cross_validate_fm(
    Y_train_df=Y_train_df,
    Y_test_df=Y_test_df,
    prediction_length=prediction_length,
    context_length=context_length,
    windows=None,
    covariates=None,
    cross_learning=False,
    chronos_forecast_func=chronos_forecast,
    model_prefix="chronos",
    verbose=False,
)
end_times_chronos_uni = time.time()
print(f"Case 2 - Univariate Forecasting (Chronos) Execution time: {int((end_times_chronos_uni - start_times_chronos_uni) // 60)} min {(end_times_chronos_uni - start_times_chronos_uni) % 60:.2f} sec")

##################### let's calculate some assertions to be sure ###################
assert(np.allclose(results_chronos_uni_df["y"], Y_test_df["y"]))
assert np.array_equal(results_chronos_uni_df["ds"].to_numpy(), Y_test_df["ds"].to_numpy())
#make sure the generated baseline predcitions have the correct lengths
assert len(results_chronos_uni_df) == len(df["unique_id"].unique().tolist()) * TEST


# Case 3: Univariate Forecasting + Covariates
start_times_chronos_uni_cov = time.time()
results_chronos_uni_cov_df = cross_validate_fm(
    Y_train_df=Y_train_df,
    Y_test_df=Y_test_df,
    prediction_length=prediction_length,
    context_length=context_length,
    windows=None,
    covariates=["day","month","is_holiday","country","store","product","holiday_name"],
    cross_learning=False,
    chronos_forecast_func=chronos_forecast,
    model_prefix="chronos",
    verbose=False,
)
end_times_chronos_uni_cov = time.time()
print(f"Case 3 - Univariate Forecasting + Covariates (Chronos) Execution time: {int((end_times_chronos_uni_cov - start_times_chronos_uni_cov) // 60)} min {(end_times_chronos_uni_cov - start_times_chronos_uni_cov) % 60:.2f} sec")

##################### let's calculate some assertions to be sure ###################
assert(np.allclose(results_chronos_uni_cov_df["y"], Y_test_df["y"]))
assert np.array_equal(results_chronos_uni_cov_df["ds"].to_numpy(), Y_test_df["ds"].to_numpy())
#make sure the generated baseline predcitions have the correct lengths
assert len(results_chronos_uni_cov_df) == len(df["unique_id"].unique().tolist()) * TEST


# Case 4: Multivariate Forecasting + Covariates (Cross-Learning)
start_times_chronos_mv_cov = time.time()
results_chronos_mv_cov_df = cross_validate_fm(
    Y_train_df=Y_train_df,
    Y_test_df=Y_test_df,
    prediction_length=prediction_length,
    context_length=context_length,
    windows=None,
    covariates=["day","month","is_holiday","country","store","product","holiday_name"],
    cross_learning=True,
    chronos_forecast_func=chronos_forecast,
    model_prefix="chronos",
    verbose=False,
)
end_times_chronos_mv_cov = time.time()
print(f"Case 4 - Multivariate Forecasting + Covariates (Cross-Learning, Chronos) Execution time: {int((end_times_chronos_mv_cov - start_times_chronos_mv_cov) // 60)} min {(end_times_chronos_mv_cov - start_times_chronos_mv_cov) % 60:.2f} sec")

##################### let's calculate some assertions to be sure ###################
assert(np.allclose(results_chronos_mv_cov_df["y"], Y_test_df["y"]))
assert np.array_equal(results_chronos_mv_cov_df["ds"].to_numpy(), Y_test_df["ds"].to_numpy())
#make sure the generated baseline predcitions have the correct lengths
assert len(results_chronos_mv_cov_df) == len(df["unique_id"].unique().tolist()) * TEST


results_chronos_mv_df.rename(columns={'chronos-50': 'chronos-mv','chronos-10':'chronos-mv-lo-80', 'chronos-90':'chronos-mv-hi-80'}, inplace=True)
results_chronos_uni_df.rename(columns={'chronos-50': 'chronos-uni','chronos-10':'chronos-uni-lo-80', 'chronos-90':'chronos-uni-hi-80'}, inplace=True)
results_chronos_uni_cov_df.rename(columns={'chronos-50': 'chronos-uni_cov','chronos-10':'chronos-uni_cov-lo-80', 'chronos-90':'chronos-uni_cov-hi-80'}, inplace=True)
results_chronos_mv_cov_df.rename(columns={'chronos-50': 'chronos-mv_cov','chronos-10':'chronos-mv_cov-lo-80', 'chronos-90':'chronos-mv_cov-hi-80'}, inplace=True)

"""Next, we try statistical models

Looking at the plots, our time series clearly show multiple seasonal patterns.

To build a stronger baseline, we'll use models that handle multiple seasonalities — specifically MSTL, MFLES, and TBATS.

To boost their performance further, we’ll explicitly identify and supply the dominant seasonalities using the code below:
"""

# compute periodogram, since all time-series in the dataset have the same seasonality
# we extract dominant seasonalities from the first time series
ts =  df[df["unique_id"]=='Belgium_KaggleMart_Kaggle Advanced Techniques']["y"]
freqs, spectrum = periodogram(ts)

# ignore zero frequency
pos_mask = freqs > 0
freqs = freqs[pos_mask]
spectrum = spectrum[pos_mask]

# find all peaks in the spectrum, here we use 5% of max power
# lower this value to get more dominant seasonalities
peaks, _ = find_peaks(spectrum, height=np.max(spectrum)*0.05)
peak_freqs = freqs[peaks]
peak_powers = spectrum[peaks]

# sort peaks by power descending
sorted_idx = np.argsort(peak_powers)[::-1]
peak_freqs = peak_freqs[sorted_idx]
peak_powers = peak_powers[sorted_idx]

# convert frequencies to periods
seasonal_periods = [int(round(1/f)) for f in peak_freqs]

print("Estimated seasonalities (in order of prominence):", seasonal_periods)

"""So, the dominant seasonalities are monthly and yearly — just as we expected from the plots."""

from statsforecast.models import (
    CrostonClassic as Croston,
    Naive,
    AutoETS,
    AutoCES,
    AutoTheta,
    DynamicOptimizedTheta,
    SeasonalNaive,
    AutoARIMA,
    IMAPA,
    CrostonOptimized,
    CrostonSBA,
    AutoTBATS,
    AutoMFLES,
    TBATS,
    MFLES,
    MSTL
)
levels = [80]

# Commented out IPython magic to ensure Python compatibility.
# %%time
# import time
# start_statistical = time.time()
# 
# sf = StatsForecast(
#     models=[Naive(),
#             SeasonalNaive(season_length=seasonality),
#             AutoETS(season_length=seasonality),
#             DynamicOptimizedTheta(season_length=seasonality),
#             AutoCES(season_length=seasonality),
#             AutoTheta(season_length=seasonality),
#             AutoARIMA(),
#             IMAPA(),
#             TBATS(season_length=[7,365]),
#             MFLES(season_length=[7,365]),
#             MSTL(season_length=[7,365]),
#             ],
#     freq='D',  n_jobs=-1, fallback_model=Naive()
# )
# 
# baseline_predictions = sf.cross_validation(df=df[["ds",'y',"unique_id"]], test_size=TEST, n_windows=None, h=prediction_length,step_size=prediction_length,level=levels)
# end_statistical = time.time()
# print(f"Execution time: {int((end_statistical - start_statistical) // 60)} min {(end_statistical - start_statistical) % 60:.2f} sec")
# 
# 
# #make sure that cross-validation works as expected and the time horizons of ground truths match!
# assert(np.allclose(baseline_predictions["y"], Y_test_df["y"]))
# assert np.array_equal(baseline_predictions["ds"].to_numpy(), Y_test_df["ds"].to_numpy())
# #make sure the generated baseline predcitions have the correct lengths
# assert len(baseline_predictions) == len(df["unique_id"].unique().tolist()) * TEST

final_predictions = pd.concat([results_chronos_mv_df[['chronos-mv', 'chronos-mv-lo-80','chronos-mv-hi-80']],
                               results_chronos_uni_df[[ 'chronos-uni', 'chronos-uni-lo-80','chronos-uni-hi-80']],
                               results_chronos_uni_cov_df[[ 'chronos-uni_cov', 'chronos-uni_cov-lo-80','chronos-uni_cov-hi-80']],
                               results_chronos_mv_cov_df[[ 'chronos-mv_cov', 'chronos-mv_cov-lo-80','chronos-mv_cov-hi-80']],
                               baseline_predictions
                               ],axis=1)

mase_seas =partial(mase, seasonality=seasonality)
rmae_baseline =partial(rmae, baseline="SeasonalNaive")
rmsse_seas =partial(rmsse, seasonality=seasonality)
mql_seas =partial(scaled_mqloss, seasonality=seasonality)

evaluation_baseline = evaluate(df=final_predictions, metrics=[smape,mae,mse, mase_seas, rmsse_seas,rmse,mqloss,rmsse_seas,mql_seas,rmae_baseline], train_df=Y_train_df,  models=['Naive',"AutoETS",'DynamicOptimizedTheta','CES','AutoTheta','AutoARIMA','IMAPA','SeasonalNaive','TBATS','MFLES','MSTL','chronos-mv',"chronos-uni", "chronos-uni_cov", "chronos-mv_cov"],level=[80],agg_fn='mean')
evaluation_baseline.set_index("metric").T.sort_index().style.highlight_min(color='green', axis=0)

"""#### Use Maximum Context-Length=1221"""

context_length=1221
prediction_length=24
num_windows = 10
TEST = prediction_length * num_windows

Y_train_df, Y_test_df =  split_train_test(df, context_length, TEST)


# Case 1: Multivariate Forecasting
start_times_chronos_mv = time.time()
results_chronos_mv_df = cross_validate_fm(
    Y_train_df=Y_train_df,
    Y_test_df=Y_test_df,
    prediction_length=prediction_length,
    context_length=context_length,
    windows=None,
    covariates=None,
    cross_learning=True,
    chronos_forecast_func=chronos_forecast,
    model_prefix="chronos",
    verbose=False,
)
end_times_chronos_mv = time.time()
print(f"Case 1 - Multivariate Forecasting (Chronos) Execution time: {int((end_times_chronos_mv - start_times_chronos_mv) // 60)} min {(end_times_chronos_mv - start_times_chronos_mv) % 60:.2f} sec")

##################### let's calculate some assertions to be sure ###################
assert(np.allclose(results_chronos_mv_df["y"], Y_test_df["y"]))
assert np.array_equal(results_chronos_mv_df["ds"].to_numpy(), Y_test_df["ds"].to_numpy())
#make sure the generated baseline predcitions have the correct lengths
assert len(results_chronos_mv_df) == len(df["unique_id"].unique().tolist()) * TEST


# Case 2: Univariate Forecasting
start_times_chronos_uni = time.time()
results_chronos_uni_df = cross_validate_fm(
    Y_train_df=Y_train_df,
    Y_test_df=Y_test_df,
    prediction_length=prediction_length,
    context_length=context_length,
    windows=None,
    covariates=None,
    cross_learning=False,
    chronos_forecast_func=chronos_forecast,
    model_prefix="chronos",
    verbose=False,
)
end_times_chronos_uni = time.time()
print(f"Case 2 - Univariate Forecasting (Chronos) Execution time: {int((end_times_chronos_uni - start_times_chronos_uni) // 60)} min {(end_times_chronos_uni - start_times_chronos_uni) % 60:.2f} sec")

##################### let's calculate some assertions to be sure ###################
assert(np.allclose(results_chronos_uni_df["y"], Y_test_df["y"]))
assert np.array_equal(results_chronos_uni_df["ds"].to_numpy(), Y_test_df["ds"].to_numpy())
#make sure the generated baseline predcitions have the correct lengths
assert len(results_chronos_uni_df) == len(df["unique_id"].unique().tolist()) * TEST


# Case 3: Univariate Forecasting + Covariates
start_times_chronos_uni_cov = time.time()
results_chronos_uni_cov_df = cross_validate_fm(
    Y_train_df=Y_train_df,
    Y_test_df=Y_test_df,
    prediction_length=prediction_length,
    context_length=context_length,
    windows=None,
    covariates=["day","month","is_holiday","country","store","product","holiday_name"],
    cross_learning=False,
    chronos_forecast_func=chronos_forecast,
    model_prefix="chronos",
    verbose=False,
)
end_times_chronos_uni_cov = time.time()
print(f"Case 3 - Univariate Forecasting + Covariates (Chronos) Execution time: {int((end_times_chronos_uni_cov - start_times_chronos_uni_cov) // 60)} min {(end_times_chronos_uni_cov - start_times_chronos_uni_cov) % 60:.2f} sec")

##################### let's calculate some assertions to be sure ###################
assert(np.allclose(results_chronos_uni_cov_df["y"], Y_test_df["y"]))
assert np.array_equal(results_chronos_uni_cov_df["ds"].to_numpy(), Y_test_df["ds"].to_numpy())
#make sure the generated baseline predcitions have the correct lengths
assert len(results_chronos_uni_cov_df) == len(df["unique_id"].unique().tolist()) * TEST


# Case 4: Multivariate Forecasting + Covariates (Cross-Learning)
start_times_chronos_mv_cov = time.time()
results_chronos_mv_cov_df = cross_validate_fm(
    Y_train_df=Y_train_df,
    Y_test_df=Y_test_df,
    prediction_length=prediction_length,
    context_length=context_length,
    windows=None,
    covariates=["day","month","is_holiday","country","store","product","holiday_name"],
    cross_learning=True,
    chronos_forecast_func=chronos_forecast,
    model_prefix="chronos",
    verbose=False,
)
end_times_chronos_mv_cov = time.time()
print(f"Case 4 - Multivariate Forecasting + Covariates (Cross-Learning, Chronos) Execution time: {int((end_times_chronos_mv_cov - start_times_chronos_mv_cov) // 60)} min {(end_times_chronos_mv_cov - start_times_chronos_mv_cov) % 60:.2f} sec")

##################### let's calculate some assertions to be sure ###################
assert(np.allclose(results_chronos_mv_cov_df["y"], Y_test_df["y"]))
assert np.array_equal(results_chronos_mv_cov_df["ds"].to_numpy(), Y_test_df["ds"].to_numpy())
#make sure the generated baseline predcitions have the correct lengths
assert len(results_chronos_mv_cov_df) == len(df["unique_id"].unique().tolist()) * TEST


results_chronos_mv_df.rename(columns={'chronos-50': 'chronos-mv','chronos-10':'chronos-mv-lo-80', 'chronos-90':'chronos-mv-hi-80'}, inplace=True)
results_chronos_uni_df.rename(columns={'chronos-50': 'chronos-uni','chronos-10':'chronos-uni-lo-80', 'chronos-90':'chronos-uni-hi-80'}, inplace=True)
results_chronos_uni_cov_df.rename(columns={'chronos-50': 'chronos-uni_cov','chronos-10':'chronos-uni_cov-lo-80', 'chronos-90':'chronos-uni_cov-hi-80'}, inplace=True)
results_chronos_mv_cov_df.rename(columns={'chronos-50': 'chronos-mv_cov','chronos-10':'chronos-mv_cov-lo-80', 'chronos-90':'chronos-mv_cov-hi-80'}, inplace=True)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# import time
# start_statistical = time.time()
# 
# sf = StatsForecast(
#     models=[Naive(),
#             SeasonalNaive(season_length=seasonality),
#             AutoETS(season_length=seasonality),
#             DynamicOptimizedTheta(season_length=seasonality),
#             AutoCES(season_length=seasonality),
#             AutoTheta(season_length=seasonality),
#             AutoARIMA(),
#             IMAPA(),
#             AutoTBATS(season_length=[7,365]),
#             AutoMFLES(season_length=[7,365],test_size=prediction_length),
#             MSTL(season_length=[7,365]),
#             ],
#     freq='D',  n_jobs=-1, fallback_model=Naive()
# )
# 
# baseline_predictions = sf.cross_validation(df=df[["ds",'y',"unique_id"]], test_size=TEST, n_windows=None, h=prediction_length,step_size=prediction_length,level=levels)
# end_statistical = time.time()
# print(f"Execution time: {int((end_statistical - start_statistical) // 60)} min {(end_statistical - start_statistical) % 60:.2f} sec")
# 
# 
# #make sure that cross-validation works as expected and the time horizons of ground truths match!
# assert(np.allclose(baseline_predictions["y"], Y_test_df["y"]))
# assert np.array_equal(baseline_predictions["ds"].to_numpy(), Y_test_df["ds"].to_numpy())
# #make sure the generated baseline predcitions have the correct lengths
# assert len(baseline_predictions) == len(df["unique_id"].unique().tolist()) * TEST

final_predictions = pd.concat([results_chronos_mv_df[['chronos-mv', 'chronos-mv-lo-80','chronos-mv-hi-80']],
                               results_chronos_uni_df[[ 'chronos-uni', 'chronos-uni-lo-80','chronos-uni-hi-80']],
                               results_chronos_uni_cov_df[[ 'chronos-uni_cov', 'chronos-uni_cov-lo-80','chronos-uni_cov-hi-80']],
                               results_chronos_mv_cov_df[[ 'chronos-mv_cov', 'chronos-mv_cov-lo-80','chronos-mv_cov-hi-80']],
                               baseline_predictions
                               ],axis=1)

mase_seas =partial(mase, seasonality=seasonality)
rmae_baseline =partial(rmae, baseline="SeasonalNaive")
rmsse_seas =partial(rmsse, seasonality=seasonality)
mql_seas =partial(scaled_mqloss, seasonality=seasonality)

evaluation_baseline = evaluate(df=final_predictions, metrics=[smape,mae,mse, mase_seas, rmsse_seas,rmse,mqloss,rmsse_seas,mql_seas,rmae_baseline], train_df=Y_train_df,  models=['Naive',"AutoETS",'DynamicOptimizedTheta','CES','AutoTheta','AutoARIMA','IMAPA','SeasonalNaive','AutoTBATS','AutoMFLES','MSTL','chronos-mv',"chronos-uni", "chronos-uni_cov", "chronos-mv_cov"],level=[80],agg_fn='mean')
evaluation_baseline.set_index("metric").T.sort_index().style.highlight_min(color='green', axis=0)

"""### Plotting Predictions"""

final_predictions_pv = final_predictions.set_index(['unique_id','ds'])
item_ids_to_plot = Y_train_df['unique_id'].unique().tolist()
plot_multiple_timeseries(Y_train_df, final_predictions_pv, item_ids_to_plot, model="MSTL",plot_intervals=True)

final_predictions_pv = final_predictions.set_index(['unique_id','ds'])
item_ids_to_plot = Y_train_df['unique_id'].unique().tolist()
plot_multiple_timeseries(Y_train_df, final_predictions_pv, item_ids_to_plot, model="chronos-mv_cov",plot_intervals=True)