# -*- coding: utf-8 -*-
"""MOIRAI_2_0_FullTutorial_Substack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K_AnzffipQPCFKGZ-AR1pZrKoNaHAgVA

## Install and import libraries

Here, I install a specific repo instance to make sure the tutorial is always reproducible.

Feel free to comment the git checkout part and use the latest instance
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip uninstall -y torch torchvision torchaudio
# !git clone https://github.com/SalesforceAIResearch/uni2ts  && \
#  cd uni2ts && \
#  git checkout 8062ef5a5660d2fea395fd1288ec9c397396c168 && \
#  pip install .
# 
# !pip install StatsForecast==2.0.2

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import torch
from sklearn.metrics import mean_squared_error, mean_absolute_error
from functools import partial

from einops import rearrange
from gluonts.dataset.pandas import PandasDataset
from gluonts.dataset.split import split

from uni2ts.eval_util.plot import plot_single, plot_next_multi
from uni2ts.model.moirai import MoiraiForecast, MoiraiModule
from uni2ts.model.moirai2 import Moirai2Forecast, Moirai2Module


from statsforecast import StatsForecast
from utilsforecast.losses import mae,mse,smape, mase
from utilsforecast.evaluation import evaluate

## set this environment variable to simulate a new format for the predictions that will be available in
## the next versions of Nixtla libraries
import os
os.environ["NIXTLA_ID_AS_COL"] = "1"

"""## Download the dataset

Our project will use the **ElectricityLoadDiagrams20112014** dataset from UCI.
This dataset contains the power usage (in KWs) of 370 clients/consumers with a 15-minute frequency. The data span 4 years (2011–2014).

Some consumers were created after 2011, so their power usage initially is zero.

For this project, we'll only use 5 time-series.The goal to predict 24 datapoints in the future.

**Note:** The MOIRAI-2 paper has not yet been released, so we do not know the full details of its pretraining data. For this comparison, we will use the Electricity dataset to evaluate MOIRAI-2 against the original MOIRAI model from an earlier tutorial.

Some foundation models are pretrained not only on the GIFT-Eval pretraining dataset but also on portions of the GIFT-Eval evaluation dataset.

Since the Electricity-hourly dataset is included in the GIFT-Eval evaluation dataset, we will resample it to a 6-hour frequency. This produces new time series with different characteristics, helping reduce the potential effects of memorization and data leakage (if any).
"""

!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00321/LD2011_2014.txt.zip
!unzip LD2011_2014.txt.zip

"""## Data Preprocessing"""

data = pd.read_csv('LD2011_2014.txt', index_col=0, sep=';', decimal=',')
data.index = pd.to_datetime(data.index)
data.sort_index(inplace=True)
data.head(5)

"""Resample to 6H to avoid potential data leakage:"""

data = data.resample('6H').mean().replace(0., np.nan)
earliest_time = data.index.min()
df=data[['MT_002',	'MT_004',	'MT_005',	'MT_006',	'MT_008' ]]

df_list = []

for label in df:

    ts = df[label]

    start_date = ts.ffill().dropna().index.min()
    end_date   = ts.bfill().dropna().index.max()

    active_range = (ts.index >= start_date) & (ts.index <= end_date)
    ts = ts[active_range].fillna(0.)

    tmp = pd.DataFrame({'power_usage': ts})
    date = tmp.index

    tmp['hours_from_start'] = (date - earliest_time).seconds / 60 / 60 + (date - earliest_time).days * 24
    tmp['hours_from_start'] = tmp['hours_from_start'].astype('int')

    tmp['days_from_start'] = (date - earliest_time).days
    tmp['date'] = date
    tmp['consumer_id'] = label
    tmp['hour'] = date.hour
    tmp['day'] = date.day
    tmp['day_of_week'] = date.dayofweek
    tmp['month'] = date.month

    #stack all time series vertically
    df_list.append(tmp)

time_df = pd.concat(df_list).reset_index(drop=True)

# match results in the original paper
time_df = time_df[(time_df['days_from_start'] >= 1096)
                & (time_df['days_from_start'] < 1346)].copy()

time_df

time_df.rename(columns={'power_usage': 'y', 'date':'ds', 'consumer_id':'unique_id'}, inplace=True)
time_df

# Note: patch_size only concerns MOIRAI-1
#  patch size: choose from {"auto", 8, 16, 32, 64, 128} see here (Figure 1): https://aihorizonforecast.substack.com/p/moirai-salesforces-foundation-transformer

prediction_length = 24
context_length = 1000
patch_size = 32
batch_size = 32
TEST = prediction_length * 10

#In our case, we choose a patch size of 32 since the frequency is mostly close to hourly.

#split our data
Y_train_df = time_df[time_df.ds<time_df['ds'].values[-(TEST) ]]
Y_test_df = time_df[time_df.ds>=time_df['ds'].values[-(TEST)]]

"""## Exploratory Data Analysis"""

# Plot all 5 time-series of the dataset

for unique_id in time_df['unique_id'].unique():
    subset = time_df[time_df['unique_id'] == unique_id]
    plt.figure(figsize=(15, 4))
    plt.plot(subset['ds'], subset['y'])
    plt.title(f'Time Series for {unique_id}')
    plt.xlabel('Date')
    plt.ylabel('Value')
    plt.show()

#number of datapoints per time-series
time_df['unique_id'].value_counts()

"""## Baseline (Statistical Models)"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# from statsforecast.models import (
#     CrostonClassic as Croston,
#     SeasonalNaive,
#     AutoETS,
#     AutoCES,
#     DynamicOptimizedTheta,
#     SeasonalNaive,
# )
# 
# sf = StatsForecast(
#     models=[SeasonalNaive(season_length= int(prediction_length/6)),
#       Croston(),
#       AutoETS(season_length= int(prediction_length/6)),
#       AutoCES(season_length=int(prediction_length/6)),
#       DynamicOptimizedTheta(season_length= int(prediction_length/6))],
#   freq='6H', n_jobs=-1)
# 
# baseline_predictions = sf.cross_validation(df=time_df, test_size=TEST, n_windows=None,h=prediction_length,step_size=prediction_length)

baseline_predictions

#We will compare the forecasts with the observed values in Y_test_df
Y_test_df

#make sure that cross-validation works as expected and the time horizons of ground truths match!
assert(np.allclose(baseline_predictions["y"], Y_test_df["y"]))

"""### Evaluate Statistical Models"""

mase_seas = partial(mase, seasonality=prediction_length)

evaluation_baseline = evaluate(df=baseline_predictions, metrics=[smape,mae,mse,mase_seas], train_df=Y_train_df,  models=['SeasonalNaive','CrostonClassic','AutoETS','CES','DynamicOptimizedTheta'])
evaluation_baseline

#statistical baseline
numeric_cols = evaluation_baseline.select_dtypes(include='number').columns
evaluation_baseline_df = evaluation_baseline.pivot_table(index='metric', values=numeric_cols, aggfunc='mean')

evaluation_baseline_df.reset_index(inplace=True)
evaluation_baseline_df

# if you don't want to use Nixtla's utilsforecast.evaluate(), you can calculate the metrics e.g. the MSE and MAE of SeasonalNaive this way:

manual_evaluation_baseline= baseline_predictions.groupby('unique_id').apply(lambda group: pd.Series({
    'MSE': mean_squared_error(group['y'], group['SeasonalNaive']),
    'MAE': mean_absolute_error(group['y'], group['SeasonalNaive'])
})).reset_index()

manual_evaluation_baseline['MSE'].mean(), manual_evaluation_baseline['MAE'].mean()
#(263.7641633912892, 10.463505969425796)

"""### Plotting Statistical Baseline Forecasts"""

baseline_predictions = baseline_predictions.set_index(['unique_id','ds'])
baseline_predictions

def plot_multiple_timeseries(train_data, predictions, item_ids_to_plot, model, plot_intervals, out_of_sample=None):

    """
    Plots multiple time series for given items, including historical data, forecasts, and observed values.

    This function generates subplots for each item in `item_ids_to_plot`, displaying:
    - The historical time series data.
    - The model's forecast.
    - The observed values (if available).
    - Optionally, out-of-sample forecasts and prediction intervals.

    Parameters:
    -----------
    train_data : pandas.DataFrame
        DataFrame containing historical time series data. It should have the columns `unique_id`, `ds` (date), and `y` (values).
    predictions : pandas.DataFrame
        DataFrame containing forecasted values. It should have the same structure as `train_data`, with additional columns for model predictions and confidence intervals.
    item_ids_to_plot : list
        A list of `unique_id`s for the items to plot.
    model : str
        The name of the model used for forecasting, which should correspond to columns in the `predictions` and `out_of_sample` DataFrames.
    plot_intervals : bool
        If `True`, the function will plot the 10%-90% prediction intervals for the forecasts.
    out_of_sample : pandas.DataFrame, optional
        DataFrame containing out-of-sample forecasts, with columns similar to `predictions`. If provided, out-of-sample forecasts and intervals will be plotted.

    Returns:
    --------
    None
        The function displays the plots and does not return any values.
    """

    colors = ['#FF6347', '#4169E1', '#3DC24C', '#FF69B4', '#8B008B']

    plt.figure(figsize=(13, 13))
    for i, item_id in enumerate(item_ids_to_plot):
        plt.subplot(5, 1, i + 1)

        y_past = train_data.set_index(['unique_id', 'ds']).loc[item_id]['y'][-100:]
        y_pred = predictions.loc[item_id]
        y_test = predictions.loc[item_id]["y"]

        plt.plot(y_past, label="Past Time Series", color=colors[0], linestyle='-')
        plt.plot(y_pred[model], label="Forecast", color=colors[1], linestyle='-')
        plt.plot(y_test, label="Observed", color=colors[2], linestyle='--')

        # Check if out_of_sample is provided and not empty
        if out_of_sample is not None and not out_of_sample.empty:
            y_out_of_sample = out_of_sample.loc[item_id]
            plt.plot(y_out_of_sample[model+'_oof'], label="Out-of-Sample", color=colors[4], linestyle='-')
            plt.fill_between(y_out_of_sample.index, y_out_of_sample[model+"_oof-0.1"], y_out_of_sample[model+"_oof-0.9"], color=colors[4], alpha=0.1, label="10%-90% OOS Confidence Interval")

        # Check if prediction intervals are provided
        if plot_intervals:
           plt.fill_between(y_pred.index, y_pred[model+"-0.1"], y_pred[model+"-0.9"], color=colors[1], alpha=0.1, label="10%-90% Test Confidence Interval")


        plt.legend()
        plt.xlabel("Time")
        plt.ylabel("Value")
        plt.title(f"Predictions for Item {item_id}")
        plt.grid(True, linestyle='--', alpha=0.6)

    plt.tight_layout()
    plt.show()

item_ids_to_plot = time_df['unique_id'].unique().tolist()
plot_multiple_timeseries(Y_train_df, baseline_predictions, item_ids_to_plot, model="SeasonalNaive",plot_intervals=False, out_of_sample=None)

"""## MOIRAI"""

# Some helper functions to convert the gluonts dataframes to pandas dataframes

def gluon_to_pandas(gluon_dataset):

  data_ds = [{ 'item_id': x['item_id'],  'start': x['start'], 'target': x['target'], 'hour': x['feat_dynamic_real'][0],'day': x['feat_dynamic_real'][1], 'day_of_week': x['feat_dynamic_real'][2], 'month': x['feat_dynamic_real'][3], 'hours_from_start': x['feat_dynamic_real'][4], 'days_from_start': x['feat_dynamic_real'][5],} for x in gluon_dataset]
  data_ds = [{
      'item_id': data['item_id'],
      'start': [date.strftime('%Y-%m-%d %H:%M:%S') for date in [data['start'] + i for i in range(len(data['target']))]],
      'target': data['target'],
      'hours_from_start': data['hours_from_start'],
      'days_from_start': data['days_from_start'],
      'day': data['day'],
      'day_of_week': data['day_of_week'],
      'month': data['month'],
      'hour': data['hour'],

  } for data in data_ds]


  pandas_df = pd.DataFrame(data_ds).explode(['start','target','hours_from_start','days_from_start','day','day_of_week','month','hour'])
  return pandas_df


def moirai_forecasts_topandas(gluon_dataset, forecast_col_name):

  data_ds = [{ 'unique_id': x.item_id,  'ds': x.start_date, forecast_col_name: x.mean, forecast_col_name+'-0.1': x.quantile(0.1),  forecast_col_name+'-0.9': x.quantile(0.9)} for x in gluon_dataset]
  data_ds = [{
      'unique_id': data['unique_id'],
      'ds': [date.strftime('%Y-%m-%d %H:%M:%S') for date in [data['ds'] + i for i in range(len(data[forecast_col_name]))]],
      forecast_col_name: data[forecast_col_name],
      forecast_col_name+'-0.1': data[forecast_col_name+'-0.1'],
      forecast_col_name+'-0.9':data[forecast_col_name+'-0.9']
  } for data in data_ds]


  pandas_df = pd.DataFrame(data_ds).explode(['ds',forecast_col_name, forecast_col_name+'-0.1',forecast_col_name+'-0.9' ])
  return pandas_df

def moirai2_forecasts_topandas(gluon_dataset, forecast_col_name):
  # x.forecast_array[4] has shape [predicion_length], containing the medians of every element in the prediction horizon. You can also use x.median
  # x.forecast_array[0] also has shape [predicion_length], containing the first out of 9 quantiles

  data_ds = [{ 'unique_id': x.item_id,  'ds': x.start_date, forecast_col_name: x.forecast_array[4], forecast_col_name+'-0.1': x.forecast_array[0],  forecast_col_name+'-0.9': x.forecast_array[8]} for x in gluon_dataset]
  data_ds = [{
      'unique_id': data['unique_id'],
      'ds': [date.strftime('%Y-%m-%d %H:%M:%S') for date in [data['ds'] + i for i in range(len(data[forecast_col_name]))]],
      forecast_col_name: data[forecast_col_name],
      forecast_col_name+'-0.1': data[forecast_col_name+'-0.1'],
      forecast_col_name+'-0.9':data[forecast_col_name+'-0.9']
  } for data in data_ds]


  pandas_df = pd.DataFrame(data_ds).explode(['ds',forecast_col_name, forecast_col_name+'-0.1',forecast_col_name+'-0.9' ])
  return pandas_df

ds = PandasDataset.from_long_dataframe(
    time_df,
    item_id="unique_id",
    feat_dynamic_real=["hour", "day", "day_of_week", "month",'hours_from_start','days_from_start'],
    target="y",
    freq="6H",
    timestamp="ds")

# Split into train/test set
train_gluon, test_template = split(
    ds, offset=-TEST
)  # here, you can use a larger value than 24, to perform rolling-forward forecasts over larger horizons
   # in our case, we use TEST = prediction_length*10 in order to evaluate on the on the whole testing horizon

# Construct rolling window evaluation
test_gluon = test_template.generate_instances(
    prediction_length=prediction_length,  # number of time steps for each prediction
    windows=TEST // prediction_length,  # number of windows in rolling window evaluation
    distance=prediction_length,  # number of time steps between each window - distance=PDT for non-overlapping windows)
)

## train_pandas_df is exactly the same with Y_train_df, but with some differences in the column and index name (format of Gluon TS)
## feel free to print Y_train_df and compare these two

## we need the train_pandas_df to compute MASE later - which requires the in-sample Seasonal Naive

train_pandas_df = gluon_to_pandas(train_gluon)
train_pandas_df

#let's verify the 2 dataframes are the same!
np.allclose(train_pandas_df['target'].astype(float).values, Y_train_df['y'].astype(float).values, rtol=1e-5, atol=1e-8)

"""### Loading the models"""

# Note 1: MOIRAI authord have released newer versions!
# Feel free to try Salesforce/moirai-1.1-R-{small/base/large}

# Note 2: It seems that MOIRAI-2 currently is pre-trained with univariate data, and does not learn any cross-variate patterns.
# That's why we set feat_dynamic_real_dim=0

def get_moirai_forecast(variant:str):

  model = MoiraiForecast(
    module=MoiraiModule.from_pretrained(f"Salesforce/moirai-1.0-R-{variant}"),
    prediction_length=prediction_length,
    context_length=context_length,
    patch_size=patch_size,
    num_samples=100,
    target_dim=1,
    feat_dynamic_real_dim=ds.num_feat_dynamic_real,
    past_feat_dynamic_real_dim=ds.num_past_feat_dynamic_real,
  )

  predictor = model.create_predictor(batch_size=batch_size)
  forecasts = predictor.predict(test_gluon.input)

  return forecasts


def get_moirai_forecast2(variant:str):

  model = Moirai2Forecast(
    module=Moirai2Module.from_pretrained( f"Salesforce/moirai-2.0-R-small"),
    prediction_length=prediction_length,
    context_length=context_length,
    #patch_size=patch_size,
    #num_samples=100,
    target_dim=1,
    feat_dynamic_real_dim=0,
    past_feat_dynamic_real_dim=ds.num_past_feat_dynamic_real,
  )

  predictor = model.create_predictor(batch_size=batch_size)
  forecasts = predictor.predict(test_gluon.input)

  return forecasts

"""### Getting Predictions for all 3 variants"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# forecasts_moirai_large = get_moirai_forecast('large')
# forecasts_moirai_base = get_moirai_forecast('base')
# forecasts_moirai_small = get_moirai_forecast('small')
# 
# forecasts_moirai2_small = get_moirai_forecast2('small')

# Basically MOIRAI returns a generator which in turns outputs the predictions
# Below is their format. Fortunately, we use the moirai_forecasts_topandas() to convert them to a pandas dataframe

# for x in forecasts_moirai_base:
#   print(x)
#   print(x.samples.shape)
#   break

# Things change a bit for MOIRAI-2
# Here, we get directly an array of shape [num_quantiles, prediction_length]

# for x in forecasts_moirai2_small:
#   print(x)
#   print(x.forecast_array.shape)
#   break

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# moirai_forecast_df_large = moirai_forecasts_topandas(forecasts_moirai_large,forecast_col_name="moirai_forecast_large")
# moirai_forecast_df_base = moirai_forecasts_topandas(forecasts_moirai_base,forecast_col_name="moirai_forecast_base")
# moirai_forecast_df_small = moirai_forecasts_topandas(forecasts_moirai_small,forecast_col_name="moirai_forecast_small")
# moirai2_forecast_df_small = moirai2_forecasts_topandas(forecasts_moirai2_small,forecast_col_name="moirai2_forecast_small")

moirai_forecast_df_base

baseline_predictions

moirai_forecast_df = pd.concat([ moirai_forecast_df_small[['unique_id', 'ds', 'moirai_forecast_small', 'moirai_forecast_small-0.1', 'moirai_forecast_small-0.9']], moirai_forecast_df_base[['moirai_forecast_base','moirai_forecast_base-0.1', 'moirai_forecast_base-0.9']], moirai_forecast_df_large[['moirai_forecast_large', 'moirai_forecast_large-0.1', 'moirai_forecast_large-0.9']], moirai2_forecast_df_small[['moirai2_forecast_small', 'moirai2_forecast_small-0.1', 'moirai2_forecast_small-0.9']]], axis=1)
moirai_forecast_df['ds'] = pd.to_datetime(moirai_forecast_df['ds'])
moirai_forecast_df[moirai_forecast_df.filter(like='moirai_forecast_').columns] = moirai_forecast_df.filter(like='moirai_forecast_').apply(pd.to_numeric)
moirai_forecast_df

## add the observed value y to the dataframe
moirai_forecast_df['y'] = Y_test_df['y'].to_list()
moirai_forecast_df

"""### Evaluate MOIRAI models"""

seasonality=prediction_length
mase_seas = partial(mase, seasonality=seasonality)

evaluation_moirai = evaluate(df=moirai_forecast_df, metrics=[smape,mae,mse,mase_seas], train_df=train_pandas_df.rename(columns={'item_id':"unique_id",'start':"ds","target":"y"}),  models=['moirai_forecast_small','moirai_forecast_base','moirai_forecast_large','moirai2_forecast_small'])
evaluation_moirai

evaluation_moirai_df = evaluation_moirai.pivot_table(index='metric', values=['moirai_forecast_small','moirai_forecast_base','moirai_forecast_large','moirai2_forecast_small'], aggfunc='mean')

evaluation_moirai_df.reset_index(inplace=True)
evaluation_moirai_df

# You can also evaluate MOIRAI manually, e.g. MOIRAI Large
manual_evaluation_moirai= moirai_forecast_df.groupby('unique_id').apply(lambda group: pd.Series({
    'MSE': mean_squared_error(group['y'], group['moirai_forecast_large']),
    'MAE': mean_absolute_error(group['y'], group['moirai_forecast_large'])
})).reset_index()

manual_evaluation_moirai['MSE'].mean(), manual_evaluation_moirai['MAE'].mean()

"""### Final Results (Statistical Models vs MOIRAI)"""

pd.concat([evaluation_baseline_df, evaluation_moirai_df.drop(columns=['metric'])], axis=1).set_index('metric').style.highlight_min(color='lightgreen', axis=1)

"""Same dataframe, more readable:"""

pd.concat([evaluation_baseline_df, evaluation_moirai_df.drop(columns=['metric'])], axis=1).set_index('metric').T.style.highlight_min(color='lightgreen', axis=0)

"""###Plotting Forecasts of MOIRAI-2"""

moirai_forecast_df["moirai2_forecast_small"] = pd.to_numeric(moirai_forecast_df["moirai2_forecast_small"]).astype("float64")
moirai_forecast_df["moirai2_forecast_small-0.1"] = pd.to_numeric(moirai_forecast_df["moirai2_forecast_small-0.1"]).astype("float64")
moirai_forecast_df["moirai2_forecast_small-0.9"] = pd.to_numeric(moirai_forecast_df["moirai2_forecast_small-0.9"]).astype("float64")

moirai_forecast_df = moirai_forecast_df.set_index(['unique_id','ds'])
moirai_forecast_df

item_ids_to_plot = time_df['unique_id'].unique().tolist()
plot_multiple_timeseries(Y_train_df, moirai_forecast_df,item_ids_to_plot=item_ids_to_plot, model='moirai2_forecast_small', plot_intervals=True, out_of_sample=None)